# Numpy and Pandas

## Numpy : consists of multi dimensional array objects and a collection of method for processing those arrays.

In [15]:
import numpy as np

## Numpy methods:

## np.array() method: creates array of n-dimensions
##   Syntax: np.array([[elements], [elements]])

In [17]:
array1 = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
array1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
## np.zeros() method: fills array with zero.
##6Syntax: np.zeros((rows, column))

In [18]:
array2 = np.zeros((2, 3))
array2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
## np.full() method: fill array with single elements
## Syntax: np.full((row, column), element)

In [19]:
array3 = np.full((2 ,4), 6)
array3

array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

In [7]:
## np.arrange() method: initialize array elements within the range.
## Syntax: np.arrange(starting element[included], ending element[excluded], stepping number[optional])

In [21]:
array4 = np.arange(5, 10)
array4

array([5, 6, 7, 8, 9])

In [22]:
array5 = np.arange(2, 12, 3)
array5

array([ 2,  5,  8, 11])

In [8]:
## np.random.randint() method: produces random integers
## Syntax: np.random.randint(starting range, ending range, number of values)

In [60]:
array6 = np.random.randint(2, 300)
array6

212

In [61]:
array7 = np.random.randint(10, 500, 5)
array7

array([ 60,  37, 145, 383, 309])

In [9]:
## shape method: changes the shape of the array 
## Syntax: 
###    checking the shape of array: array_name.shape
###    changing shape of array: array_name.shape = (row, column)

In [64]:
array8 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90], [100, 110, 120]])
array8.shape

(4, 3)

In [69]:
array8.shape = (3, 4)
array8.shape

(3, 4)

In [10]:
## np.vstack() method: to vertically join the arrays.
## Syntax: np.vstack((array1, array2, ...))

In [70]:
array9 = np.array([[1, 2, 3], [4, 5, 6]])
array10 = np.array([[11, 12,13], [14, 15, 16]])

array11 = np.vstack((array9, array10))
array11

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [11]:
## np.hstack() method: to join arrays horizontally.
## Syntax: np.hstack((array1, array2, ...))

In [71]:
array12 = np.array([[1, 2, 3], [4, 5, 6]])
array13 = np.array([[11, 12,13], [14, 15, 16]])

array14 = np.hstack((array12, array13))
array14

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [12]:
## np.column_stack() method: to join arrays in a column
## Syntax: np.column_stack((array1, array2, ...))

In [72]:
array15 = np.array([[1, 2, 3], [4, 5, 6]])
array16 = np.array([[11, 12,13], [14, 15, 16]])

array17 = np.column_stack((array15, array16))
array17

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [13]:
## np.intersect1d() method: returns common elements of the two arrays.
## Syntax: np.intersect1d(array1, array2)

In [76]:
array18 = np.array([[1, 2, 3], [4, 5, 6]])
array19 = np.array([[11, 12, 13], [4, 5, 6]])

array20 = np.intersect1d(array18, array19)
array20

array([4, 5, 6])

In [78]:
array21 = np.intersect1d(array19, array18)
array21

array([4, 5, 6])

In [ ]:
## np.setdiff1d() method: returns the unique elements in the first array.
## Syntax: np.setdiff1d(array1, array2)

In [83]:
array22 = np.array([[1, 2, 3], [4, 5, 6]])
array23 = np.array([[11, 12, 13], [4, 5, 6]])

array24 = np.setdiff1d(array22, array23)
array24

array([1, 2, 3])

In [84]:
array25 = np.setdiff1d(array23, array22)
array25

array([11, 12, 13])